[package]
name = "giglizip-compress"
version = "0.1.0"
authors = ["Junaid Ali Shah Gigli (overview.jjj@gmail.com)"]
description = "A fast, multi-algorithm compression CLI and library."
license = "MIT OR Apache-2.0"
maintainer = "Junaid Ali Shah Gigli (overview.jjj@gmail.com)"

[dependencies]

[files]
"target/release/giglizip-compress" = "/usr/bin/giglizip-compress"
# Add man page if available
# "docs/giglizip-compress.1" = "/usr/share/man/man1/giglizip-compress.1"
